#' Title A pipeline of run RNA-seq DEGs analysis and mini database of Schistosoma japonicum
#'
#' @param count_data file path of count matrix which generated by previous RNA-seq pipeline,
#' eg: "2.Results/SnakePipe_outputs_test/featureCounts/counts.tsv"
#' @param group_a_name group a name eg:GFP
#' @param group_a_samples a list of samples in group A you choose, must in the colname of count_data
#' @param group_b_samples a list of samples in group B you choose, must in the colname of count_data
#' @param group_b_name group b name eg:dsNFY
#' @param batch if have batch effect, eg c(1,1,1,2,2,1),1~ batch1,2~ batch2
#' @param pheno_file if group > 8, please provide pheno info in a csv file format.
#' @param group_c_name group names
#' @param group_c_samples a list of samples in group , must in the colname of count_data
#' @param group_d_name group names
#' @param group_d_samples a list of samples in group , must in the colname of count_data
#' @param group_e_name group names
#' @param group_e_samples a list of samples in group , must in the colname of count_data
#' @param group_f_name group names
#' @param group_f_samples a list of samples in group , must in the colname of count_data
#' @param group_g_name group names
#' @param group_g_samples a list of samples in group , must in the colname of count_data
#' @param group_h_name group names
#' @param group_h_samples a list of samples in group , must in the colname of count_data
#' @param groupList
#'
#' @return a dds class for downstream analysis
#' @export
#'
#' @examples dds <- run_DESeq2(
#'   count_data = "~/Projects/RNASeq_CGW_20221014/2.Results/SnakePipe_outputs/featureCounts/counts.tsv",
#'   group_a_name = 'GFP',
#'   group_a_samples  = c("G.F1","G.F3","G.M"),
#'   group_b_name = 'WSS',
#'   group_b_samples = c("W.F1","W.F2","W.M1")
#' )
oldrun_DESeq2 <- function(count_data,groupList=c('GFP','dsRNA'),
                       group_a_name=NULL, group_a_samples=NULL,
                       group_b_name=NULL, group_b_samples=NULL,
                       group_c_name=NULL, group_c_samples=NULL,
                       group_d_name=NULL, group_d_samples=NULL,
                       group_e_name=NULL, group_e_samples=NULL,
                       group_f_name=NULL, group_f_samples=NULL,
                       group_g_name=NULL, group_g_samples=NULL,
                       group_h_name=NULL, group_h_samples=NULL,
                       pheno_file = '',
                       batch = NULL){
  data <- utils::read.table(count_data,header = T)
  #create a list of all samples for this current comparison
  samples_for_comparison = c(group_a_samples,
                             group_b_samples,
                             group_c_samples,
                             group_d_samples,
                             group_e_samples,
                             group_f_samples,
                             group_g_samples,
                             group_h_samples)
  #define the class factor for this pair of sample sets
  group = factor(c(rep(group_a_name,length(group_a_samples)),
                   rep(group_b_name,length(group_b_samples)),
                   rep(group_c_name,length(group_c_samples)),
                   rep(group_d_name,length(group_d_samples)),
                   rep(group_e_name,length(group_e_samples)),
                   rep(group_f_name,length(group_f_samples)),
                   rep(group_g_name,length(group_g_samples)),
                   rep(group_h_name,length(group_h_samples))
  ))

  if (is.null(samples_for_comparison)) {
    for (groupName in groupList) {
      samples_for_comparison = base::append(samples_for_comparison,colnames(data)[stringr::str_which(colnames(data), groupName)])
      group = base::append(group,rep(groupName,length(stringr::str_which(colnames(data), groupName))))
      }
    group = as.factor(group)
  }
  #create a simplified data matrix for only these samples
  rawdata = data[,samples_for_comparison]

  # create a data.frame of pheno info
  if (file.exists(pheno_file)) {
    pheno <- utils::read.csv(pheno_file,header = TRUE)
    colnames(pheno) <- c("Sample","Condition")
    rownames(pheno) <- pheno$Sample
    pheno$Condition <- as.factor(pheno$Condition)
    rawdata = data[,pheno$Sample]
  }else{
    pheno <- data.frame(Sample=colnames(rawdata),Condition= group)
    rownames(pheno) <- pheno$Sample
  }

  # if the data exist batch effect
  if (!is.null(batch)) {
    pheno$batch <- batch
    pheno$batch <- as.factor(pheno$batch)
    dds <- DESeq2::DESeqDataSetFromMatrix(countData = rawdata, colData = pheno, design = ~  batch + Condition)
    dds <- dds[rowSums(DESeq2::counts(dds)) >= 5,]
    dds <- DESeq2::DESeq(dds)
  }else{
    dds <- DESeq2::DESeqDataSetFromMatrix(countData = rawdata, colData = pheno, design = ~ Condition)
    dds <- dds[rowSums(DESeq2::counts(dds)) >= 5,]
    dds <- DESeq2::DESeq(dds)
  }
  return(dds)
}


#' Title get different expression results
#'
#' @param dds dds
#' @param group default.name = "Condition"
#' @param x 'group1'
#' @param y 'group1'
#' @param p_cutoff  default: 0.05
#' @param FC_cutoff  default: 1
#'
#' @return
#' @export
#'
#' @examples
get_mRNA_diff <- function(dds=dds,group="Condition",x,y,p_cutoff=0.05,FC_cutoff=1){
  res <- DESeq2::results(dds, contrast = c(group, x,y))
  SYMBOL <- rownames(res)
  Res <- cbind(SYMBOL,res)
  rankRes <- as.data.frame(res)
  geneList = rankRes$log2FoldChange
  names(geneList)  = rownames(rankRes)
  geneList <- sort(geneList,decreasing = T)
  diff_gene <-subset(res, padj< p_cutoff & (log2FoldChange > FC_cutoff | log2FoldChange < -FC_cutoff))
  up_gene <-subset(res, padj < p_cutoff & (log2FoldChange > FC_cutoff))
  down_gene <-subset(res, padj < p_cutoff & (log2FoldChange < -FC_cutoff))
  SYMBOL <- rownames(diff_gene)
  diff_gene <- cbind(SYMBOL, diff_gene)
  SYMBOL <- rownames(up_gene)
  up_gene <- cbind(SYMBOL, up_gene)
  up_gene <- up_gene[order(up_gene$padj),]
  up_gene$Annotation <- id2name[up_gene$SYMBOL,"Note"]
  SYMBOL <-rownames(down_gene)
  down_gene <- cbind(SYMBOL, down_gene)
  down_gene <- down_gene[order(down_gene$padj),]
  down_gene$Annotation <- id2name[down_gene$SYMBOL,"Note"]
  group <- c(x,y)
  Diff <-list(Diff_gene=diff_gene,up_gene=up_gene,down_gene=down_gene,Res=Res,rankGeneList=geneList,Group=group)
  return(Diff)
}


#' Title
#'
#' @param count_data
#' @param group_a_name
#' @param group_a_samples
#' @param group_b_name
#' @param group_b_samples
#' @param pheno_file
#' @param batch
#' @param p_cutoff
#' @param FC_cutoff
#' @param save_Plot
#' @param file_Dir
#' @param groupList
#' @param group_c_name
#' @param group_c_samples
#' @param group_d_name
#' @param group_d_samples
#' @param group_e_name
#' @param group_e_samples
#' @param group_f_name
#' @param group_f_samples
#' @param group_g_name
#' @param group_g_samples
#' @param group_h_name
#' @param group_h_samples
#'
#' @return
#' @export
#'
#' @examples
run_RNASeq <- function(count_data,groupList=c('GFP','dsRNA'),
                       group_a_name=NULL, group_a_samples=NULL,
                       group_b_name=NULL, group_b_samples=NULL,
                       group_c_name=NULL, group_c_samples=NULL,
                       group_d_name=NULL, group_d_samples=NULL,
                       group_e_name=NULL, group_e_samples=NULL,
                       group_f_name=NULL, group_f_samples=NULL,
                       group_g_name=NULL, group_g_samples=NULL,
                       group_h_name=NULL, group_h_samples=NULL,
                       pheno_file = '',
                       batch = NULL,
                       p_cutoff=0.05,
                       FC_cutoff=1,
                       save_Plot=TRUE,
                       file_Dir = './'
                       ){
  dds <- run_DESeq2(count_data,groupList,
                    group_a_name, group_a_samples,
                    group_b_name, group_b_samples,
                    group_c_name, group_c_samples,
                    group_d_name, group_d_samples,
                    group_e_name, group_e_samples,
                    group_f_name, group_f_samples,
                    group_g_name, group_g_samples,
                    group_h_name, group_h_samples,
                    pheno_file,
                    batch)
  # plot PCA for samples
  plot_PCA(dds,save_Plot,file_Dir)
  contrast = utils::combn(groupList,2)
  for (i in ncol(contrast)) {
    # get the different expression analysis results form dds object
    diff_res <- get_mRNA_diff(dds,group="Condition",x = contrast[1,i],y = contrast[2,i],p_cutoff,FC_cutoff)
    # save results to files

    DEtoXlSX(diff_res,file_Dir)
    GOtoXlSX(diff_res,file_Dir)
    GSEAtoXlSX(diff_res,file_Dir,pvalueCutoff = 0.5)
    # save all plots
    Plot_volcano(diff_res,file_Dir,save_Plot)
    Plot_heatmap(diff_res,file_Dir,dds = dds)
    PlotKEGG(diff_res,file_Dir)
    Plot_DE_GOTerms(diff_res,file_Dir,p_cutoff = 0.05)
  }

}


